/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vehicle;

import java.awt.event.KeyEvent;
import java.sql.Connection;  
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SAYS
 */
public class MakePayment extends javax.swing.JFrame {

    
    Connection con;
    PreparedStatement pst ; 
    PreparedStatement pst2 ; 
    PreparedStatement pst3 ; 
    ResultSet rs;
    
    /**
     * Creates new form MakePayment
     */
    public MakePayment() {
        initComponents();
        table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtRent = new javax.swing.JTextField();
        txtDelay = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtCust = new javax.swing.JTextField();
        txtVeh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Payment"));

        jLabel1.setText("Customer ID");

        jLabel2.setText("Rent Fee");

        jLabel3.setText("Delay Charges");

        jButton1.setText("Make Payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRentActionPerformed(evt);
            }
        });

        txtDelay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDelayActionPerformed(evt);
            }
        });
        txtDelay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDelayKeyPressed(evt);
            }
        });

        jLabel4.setText("Total Fee");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        txtCust.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustKeyPressed(evt);
            }
        });

        jLabel5.setText("Vehicle ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDelay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCust, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVeh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVeh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCust, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDelay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Veh ID", "Cust ID", "Rent  Fee", "Delay Fee", "Total Fee"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDelayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDelayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDelayActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        

    try {
        String vehc_id = txtCust.getText();
        String custm_id = txtVeh.getText();
        String rent = txtRent.getText();
        String delay = txtDelay.getText();
        String el = txtTotal.getText();

        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/carrental", "root", "");

        pst3 = con.prepareStatement("INSERT INTO pay (veh_id, cust_id, rent_fee, delay_fee, total_fee) VALUES (?, ?, ?, ?, ?)");
        pst3.setString(1, vehc_id);
        pst3.setString(2, custm_id);
        pst3.setString(3, rent);
        pst3.setString(4, delay);
        pst3.setString(5, el);
        pst3.executeUpdate();

        pst2 = con.prepareStatement("DELETE FROM rental WHERE cust_id = ?");
        pst2.setString(1, custm_id);
        pst2.executeUpdate();

        JOptionPane.showMessageDialog(this, "Update Saved");
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(rentail.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Error: Failed to save the update");
    } finally {
        try {
            if (pst3 != null) {
                pst3.close();
            }
            if (pst2 != null) {
                pst2.close();
            }
            if (con != null) {
                con.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(rentail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


        
//
//        try {
//
//            String vehc_id = txtVeh.getText();
//            String custm_id = txtCust.getText();
//            String rent = txtRent.getText();
//            String delay = txtDelay.getText();
//            String el = txtTotal.getText();
//
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            con = DriverManager.getConnection("jdbc:mysql://localhost/carrental", "root", "");
//
//            pst3 = con.prepareStatement("insert into pay (veh_id,cust_id,rent_fee,delay_fee,total_fee)values(?,?,?,?,?)");
//            pst3.setString(1,vehc_id);
//            pst3.setString(1,custm_id);
//            pst3.setString(2,rent);
//            pst3.setString(3,delay);
//            pst3.setString(4,el);
//            pst3.executeUpdate();
//
//            //            pst = con.prepareStatement("update car_reg set available = 'Yes' where car_reg = ?  ");
//            //            pst.setString(1, custm_id);
//            //            pst.executeUpdate();
//
//            pst2 = con.prepareStatement("Delete from rental where cust_id = ?  ");
//            pst2.setString(1, custm_id);
//            pst2.executeUpdate();
//
//            JOptionPane.showMessageDialog(this, "Update Saved");
//
//        }
//        catch (ClassNotFoundException ex)
//        {
//            Logger.getLogger(rentail.class.getName()).log(Level.SEVERE, null, ex);
//
//        }
//        catch (SQLException ex)
//        {
//            Logger.getLogger(rentail.class.getName()).log(Level.SEVERE, null, ex);
//
//        }
//
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRentActionPerformed

    private void txtDelayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDelayKeyPressed


    if(evt.getKeyCode() == KeyEvent.VK_ENTER){    
        
                    
            
            String fee = txtRent.getText();
            int fee1 = Integer.parseInt(fee);
            
            String delay = txtDelay.getText();
            int delay1 = Integer.parseInt(delay);
            
            int tot = (fee1 + delay1);
            txtTotal.setText(String.valueOf(tot));
            
            
            

    }    



//        try {
//            // TODO add your handling code here:
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            con = DriverManager.getConnection("jdbc:mysql://localhost/carrental","root","");
//            pst = con.prepareStatement("SELECT fee FROM rental" );
//            rs = pst.executeQuery();
//            
//            if(rs.next()==false)
//                {
//                    JOptionPane.showMessageDialog(null, "Error");
//                }
//                else
//                {
//                   int fee = rs.getInt("fee");
//                   txtRent.setText(String.valueOf(fee));
//                   
//                   pst = con.prepareStatement("SELECT fine FROM returncar" );
//                   rs = pst.executeQuery();
//                   
//                   int fine = rs.getInt("fine");
//                   txtDelay.setText(String.valueOf(fine));
//                   
//                    int totalFee = fee+fine;
//                    txtTotal.setText(String.valueOf(totalFee));
//                }
//            
//            
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(MakePayment.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(MakePayment.class.getName()).log(Level.SEVERE, null, ex);
//        }

        
    }//GEN-LAST:event_txtDelayKeyPressed

    private void txtCustKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustKeyPressed
        // TODO add your handling code here:

    if (evt.getKeyCode() == KeyEvent.VK_ENTER){

        try {
        String cos = txtCust.getText();
        pst = con.prepareStatement("SELECT car_id, cust_id, fee, NULL AS fine FROM rental WHERE cust_id = ? AND car_id = ? UNION SELECT  car_id,  cust_id, fine, NULL AS fee FROM returncar WHERE cust_id = ? AND car_id = ?");
        pst.setString(1, cos);
        pst.setString(2, cos);
        pst.setString(3, cos);
        pst.setString(4, cos);
        rs = pst.executeQuery();

        if (rs.next()) {
            
            int fee = rs.getInt("fee");
            txtRent.setText(String.valueOf(fee));

            int fine = rs.getInt("fine");
            txtDelay.setText(String.valueOf(fine));

            int totalFee = fee + fine;
            txtTotal.setText(String.valueOf(totalFee));
        }
    } catch (SQLException ex) {
        // Handle the exception
        ex.printStackTrace();
    }
}
        
//    if (evt.getKeyCode() == KeyEvent.VK_ENTER){ 
//        try {
//    Class.forName("com.mysql.cj.jdbc.Driver");
//    
//    String veh = txtVeh.getText();
//    String cust = txtCust.getText();
//    
//    con = DriverManager.getConnection("jdbc:mysql://localhost/carrental", "root", "");
//    pst = con.prepareStatement("SELECT fee FROM rental WHERE car_id = ? AND cust_id = ?");
//    pst.setString(1, veh); // Replace 'car_id' with the actual car ID value
//    pst.setString(2, cust);
//    rs = pst.executeQuery();
//
//    if (rs.next()==false) {
//        JOptionPane.showMessageDialog(null, "Error: No data found in the rental table");
//    } else {
//        
//        
//        int fee = rs.getInt("fee");
//        txtRent.setText(String.valueOf(fee));
//
//        pst = con.prepareStatement("SELECT fine FROM returncar car_id = ? AND cust_id = ?");
//        pst.setString(1, veh); // Replace 'car_id' with the actual car ID value
//        pst.setString(2, cust);
//        rs = pst.executeQuery();
//
//        if (!rs.next()) {
//            JOptionPane.showMessageDialog(null, "Error: No data found in the returncar table");
//        } else {
//            int fine = rs.getInt("fine");
//            txtDelay.setText(String.valueOf(fine));
//
//            int totalFee = fee + fine;
//            txtTotal.setText(String.valueOf(totalFee));
//        }
//    }
//} catch (ClassNotFoundException ex) {
//    Logger.getLogger(MakePayment.class.getName()).log(Level.SEVERE, null, ex);
//} catch (SQLException ex) {
//    Logger.getLogger(MakePayment.class.getName()).log(Level.SEVERE, null, ex);
////} finally {
////    try {
////        if (rs != null) {
////            rs.close();
////        }
////        if (pst != null) {
////            pst.close();
////        }
////        if (con != null) {
////            con.close();
////        }
////    } catch (SQLException ex) {
////        Logger.getLogger(MakePayment.class.getName()).log(Level.SEVERE, null, ex);
////    }
//        }
//    }
    }//GEN-LAST:event_txtCustKeyPressed

    
    
     private void table_update() {
        int CC;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/carrental","root","");
            pst = con.prepareStatement("SELECT * FROM pay");
             ResultSet Rs = pst.executeQuery();
            
   
            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) jTable1.getModel();
            DFT.setRowCount(0);

            while (Rs.next()) {
                Vector v2 = new Vector();
           
                for (int ii = 1; ii <= CC; ii++) {
                    v2.add(Rs.getString("veh_id"));
                    v2.add(Rs.getString("cust_id"));
                    v2.add(Rs.getString("rent_fee"));
                    v2.add(Rs.getString("delay_fee"));
                    v2.add(Rs.getString("total_fee"));
                    
                }

                DFT.addRow(v2);
            }
        } catch (Exception e) {
        }
    }  
     
     
     
 
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakePayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCust;
    private javax.swing.JTextField txtDelay;
    private javax.swing.JTextField txtRent;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtVeh;
    // End of variables declaration//GEN-END:variables
}
